version: "3.8"

services:
  postgresql:
    image: postgres:alpine
    container_name: postgres_test
    environment:
      - POSTGRES_PASSWORD=contrasena
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql:5432/test
      - SONARQUBE_JDBC_USERNAME=postgres
      - SONARQUBE_JDBC_PASSWORD=contrasena
    ports:
      - "9000:9000"
    networks:
      - mynetwork
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
  block14-testing:
    image: myvalidation
    networks:
      - mynetwork
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
networks:
  mynetwork:
    driver: bridge
volumes:
  sonarqube_data: {}
  sonarqube_extensions: {}
  sonarqube_logs: {}